### ISSUE TITLE
Write a better README.md

### ISSUE THREAD

**Issue by agonzalezio** [agonzalezio/tailpine#4]
Help is needed to write a better readme for users.

The main purpose of this template is to be a simple HTML template which everyone can use to quick start a web development project easily with the flexibility and beautiful UI customization Tailwind brings, and the minimal yet powerful dom manipulation Alpine offers.

These both are a good match for modern and fast web development. Tailpine it's the template everyone can use to start a web project in less than a minute.

The Readme file need to have a clear message on what's the project's purpose and how to get started with it. It's important to be clear that even if the project is using npm you can just edit the HTML files and ditch the package runtime to start a project, of course, it's recommended to reduce production file size through the `build` command.

Recommended instructions should be included, and describe what does each command do. Optionally, feel free to use a friendly voice and/or suggest improvements.

_Please use a neutral or inclusive language, and be clear and concise with instructions so everyone can understand and get the project up and running._

**Comment by d3fau7t** [comment]
Could I pick this up?

**Comment by agonzalezio** [comment]
@d3fau7t sure, you might notice I've made some substantial changes to repo structure.

In summary:

- I've divided the project in two options.
- `src` = the most complete option with minification and CSS purging using _parcel-bundler_ (requires npm).
- `public` = the just copy-edit-upload option for this template (does not need anything else to be used).

Please feel welcome to comment about any issue you have.
